import '../models/food.dart';
import '../db/database_helper.dart';

class FoodService {
  final DatabaseHelper _db = DatabaseHelper.instance;

  /// Fetch all foods
  Future<List<Food>> getFoods() async {
    try {
      final db = await _db.database;
      final result = await db.query('foods');
      print(result);
      return result.map((map) => Food.fromMap(map)).toList();
    } catch (e) {
      throw Exception('Failed to load foods: $e');
    }
  }

  /// Get food by ID
  Future<Food?> getFoodById(int id) async {
    try {
      final db = await _db.database;
      final result = await db.query('foods', where: 'id = ?', whereArgs: [id]);

      if (result.isNotEmpty) {
        return Food.fromMap(result.first);
      }
      return null;
    } catch (e) {
      throw Exception('Failed to load food: $e');
    }
  }

  /// Create new food (ID is auto-generated by SQLite)
  Future<Food> createFood({
    required String name,
    required String description,
    required double price,
    required String manufacturer,
    String? image,
  }) async {
    try {
      final db = await _db.database;

      final data = {
        'name': name,
        'description': description,
        'price': price,
        'manufacturer': manufacturer,
        'image': image,
      };

      // SQLite generates ID
      final id = await db.insert('foods', data);

      return Food(
        id: id, // now int
        name: name,
        description: description,
        price: price,
        manufacturer: manufacturer,
        image: image,
      );
    } catch (e) {
      throw Exception('Failed to create food: $e');
    }
  }

  /// Update food
  Future<void> updateFood(Food food) async {
    try {
      final db = await _db.database;
      await db.update(
        'foods',
        food.toMap(),
        where: 'id = ?',
        whereArgs: [food.id],
      );
    } catch (e) {
      throw Exception('Failed to update food: $e');
    }
  }

  /// Delete food
  Future<void> deleteFood(int id) async {
    try {
      final db = await _db.database;
      await db.delete('foods', where: 'id = ?', whereArgs: [id]);
    } catch (e) {
      throw Exception('Failed to delete food: $e');
    }
  }
}
